In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [3]:
df = pd.read_csv('emails.csv')

In [4]:
df.head()

text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [5]:
df.shape

(5728, 2)

In [6]:
df.drop_duplicates(inplace=True)

In [7]:
df.shape

(5695, 2)

In [8]:
df['text']

0       Subject: naturally irresistible your corporate...
1       Subject: the stock trading gunslinger  fanny i...
2       Subject: unbelievable new homes made easy  im ...
3       Subject: 4 color printing special  request add...
4       Subject: do not have money , get software cds ...
                              ...                        
5723    Subject: re : research and development charges...
5724    Subject: re : receipts from visit  jim ,  than...
5725    Subject: re : enron case study update  wow ! a...
5726    Subject: re : interest  david ,  please , call...
5727    Subject: news : aurora 5 . 2 update  aurora ve...
Name: text, Length: 5695, dtype: object

In [9]:
df['text'][0]

"Subject: naturally irresistible your corporate identity  lt is really hard to recollect a company : the  market is full of suqgestions and the information isoverwhelminq ; but a good  catchy logo , stylish statlonery and outstanding website  will make the task much easier .  we do not promise that havinq ordered a iogo your  company will automaticaily become a world ieader : it isguite ciear that  without good products , effective business organization and practicable aim it  will be hotat nowadays market ; but we do promise that your marketing efforts  will become much more effective . here is the list of clear  benefits : creativeness : hand - made , original logos , specially done  to reflect your distinctive company image . convenience : logo and stationery  are provided in all formats ; easy - to - use content management system letsyou  change your website content and even its structure . promptness : you  will see logo drafts within three business days . affordability : your  ma

In [11]:
import nltk
import string
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [12]:
from nltk.corpus import stopwords, words

In [13]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [14]:
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'on

**Text Preprocessing**

In [16]:
def clean_text(text):
  remove_punc1 = [char for char in text if char not in string.punctuation]
  return remove_punc1

In [17]:
df['text'].head(1).apply(clean_text)

0    [S, u, b, j, e, c, t,  , n, a, t, u, r, a, l, ...
Name: text, dtype: object

In [18]:
def clean_text(text):
  remove_punc1 = [char for char in text if char not in string.punctuation]
  remove_punc2 = ''.join(remove_punc1)
  return remove_punc2

In [19]:
df['text'].head(1).apply(clean_text)

0    Subject naturally irresistible your corporate ...
Name: text, dtype: object

In [20]:
def clean_text(text):
  remove_punc1 = [char for char in text if char not in string.punctuation]
  remove_punc2 = ''.join(remove_punc1)
  stop_words_remove = [word for word in remove_punc2.split() if word.lower() not in stopwords.words('english')]
  return stop_words_remove

In [22]:
df['text'].head(5).apply(clean_text)

0    [Subject, naturally, irresistible, corporate, ...
1    [Subject, stock, trading, gunslinger, fanny, m...
2    [Subject, unbelievable, new, homes, made, easy...
3    [Subject, 4, color, printing, special, request...
4    [Subject, money, get, software, cds, software,...
Name: text, dtype: object

**Feature Extration**

In [23]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [25]:
tf = TfidfVectorizer(analyzer=clean_text).fit_transform(df['text'])

In [28]:
from sklearn.model_selection import train_test_split as tts

In [29]:
xtrain,xtest,ytrain,ytest = tts(tf,df['spam'],test_size=0.3,random_state=45)

In [30]:
from sklearn.naive_bayes import GaussianNB, MultinomialNB,BernoulliNB

**MultinomialNB**

In [31]:
ml = MultinomialNB()

In [32]:
ml.fit(xtrain,ytrain)

MultinomialNB()

In [33]:
ml.score(xtest,ytest)

0.8899941486249269

In [34]:
ml.predict(xtest)

array([0, 0, 0, ..., 0, 0, 0])

**BernoulliNB**

In [35]:
bn = BernoulliNB()

In [36]:
bn.fit(xtrain,ytrain)

BernoulliNB()

In [37]:
bn.score(xtest,ytest)

0.9824458747805734

In [38]:
bn.predict(xtest)

array([0, 0, 0, ..., 0, 0, 0])

**GaussianNB**

In [43]:
tf

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 562930 stored elements and shape (5695, 37229)>

In [44]:
tf.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [50]:
xtrain,xtest,ytrain,ytest = tts(tf.toarray(),df['spam'],test_size=0.3,random_state=251)

In [51]:
gs = GaussianNB().fit(xtrain,ytrain)

In [53]:
accuracy = gs.score(xtest,ytest)

In [54]:
accuracy

0.9637214745465185

In [55]:
gs.predict(xtest)

array([0, 0, 1, ..., 0, 0, 0])